FROM java:8-jdk-alpine

COPY ./target/Spring-Docker-App-Demo-0.0.1-SNAPSHOT.jar /usr/app/

WORKDIR /usr/app

RUN sh -c 'touch Spring-Docker-App-Demo-0.0.1-SNAPSHOT.jar'

ENTRYPOINT["java","-jar","Spring-Docker-App-Demo-0.0.1-SNAPSHOT.jar"]